cache:
  paths:
  - pca_webservice/

stages:
  - build
  - deploy

build and push:
  stage: build
  image: docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSOWORD $DOCKER_SERVER 
    - docker build -t $IMAGE_NAME -t $DOCKER_SERVER/$IMAGE_NAME:$CI_COMMIT_REF_SLUG -t $DOCKER_SERVER/$IMAGE_NAME:latest .
    - docker push $DOCKER_SERVER/$IMAGE_NAME:$CI_COMMIT_REF_SLUG
    - docker push $DOCKER_SERVER/$IMAGE_NAME:latest
    
mirror-git:
  stage: deploy
  image: alpine
  cache: {}
  before_script:
    - apk update
    - apk add git
  script:
    - git clone --mirror ${CI_REPOSITORY_URL} project
    - cd project
    - git remote add activage ${ACTIVAGE_PROJECT_URL}
    - git push --mirror activage
 #   - cd -
 #   - git clone --mirror ${CI_REPOSITORY_URL/\.git/\.wiki\.git} wiki
 #   - cd wiki
 #   - git remote add activage ${ACTIVAGE_PROJECT_URL}.wiki.git
 #   - git push --mirror activage

